name: Pull Request Caller

on:
  pull_request:

jobs:
  pull_request:
    uses: kochavalabs/.github/.github/workflows/go_app_pull_requests.yml@v0.0.3
    with:
      GH_CI_USER: mazzaroth-dev
      GOPRIVATE: "github.com/kochavalabs"
    secrets:
      GH_CI_PAT: ${{ secrets.GH_CI_PAT }}
