name: Release Docker Version Caller

on:
  release:
    types:
      - created

jobs:
  release:
    uses: kochavalabs/.github/.github/workflows/go_app_release.yml@v0.0.3
    with:
      GH_CI_USER: mazzaroth-dev
      GOPRIVATE: "github.com/kochavalabs"
    secrets:
      GH_CI_PAT: ${{ secrets.GH_CI_PAT }}
      CONTAINER_REGISTRY: "gcr.io/kl-i-cicd-kwpj"
      CONTAINER_REGISTRY_JSON_KEY: ${{ secrets.GH_IMG_PUBLISH_JSON_KEY }}
